// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: GolangLab.proto

package GolangLabSvr

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 定义发送信息
type TestRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid   *uint64 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Question *string `protobuf:"bytes,2,opt,name=question" json:"question,omitempty"`
}

func (x *TestRQ) Reset() {
	*x = TestRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GolangLab_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRQ) ProtoMessage() {}

func (x *TestRQ) ProtoReflect() protoreflect.Message {
	mi := &file_GolangLab_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRQ.ProtoReflect.Descriptor instead.
func (*TestRQ) Descriptor() ([]byte, []int) {
	return file_GolangLab_proto_rawDescGZIP(), []int{0}
}

func (x *TestRQ) GetUserid() uint64 {
	if x != nil && x.Userid != nil {
		return *x.Userid
	}
	return 0
}

func (x *TestRQ) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

// 定义接收信息
type TestRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid *uint64 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Answer *string `protobuf:"bytes,2,opt,name=answer" json:"answer,omitempty"`
}

func (x *TestRS) Reset() {
	*x = TestRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GolangLab_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRS) ProtoMessage() {}

func (x *TestRS) ProtoReflect() protoreflect.Message {
	mi := &file_GolangLab_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRS.ProtoReflect.Descriptor instead.
func (*TestRS) Descriptor() ([]byte, []int) {
	return file_GolangLab_proto_rawDescGZIP(), []int{1}
}

func (x *TestRS) GetUserid() uint64 {
	if x != nil && x.Userid != nil {
		return *x.Userid
	}
	return 0
}

func (x *TestRS) GetAnswer() string {
	if x != nil && x.Answer != nil {
		return *x.Answer
	}
	return ""
}

var File_GolangLab_proto protoreflect.FileDescriptor

var file_GolangLab_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x4c, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x47, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x4c, 0x61, 0x62, 0x53, 0x76, 0x72, 0x22,
	0x3c, 0x0a, 0x06, 0x54, 0x65, 0x73, 0x74, 0x52, 0x51, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a,
	0x06, 0x54, 0x65, 0x73, 0x74, 0x52, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
}

var (
	file_GolangLab_proto_rawDescOnce sync.Once
	file_GolangLab_proto_rawDescData = file_GolangLab_proto_rawDesc
)

func file_GolangLab_proto_rawDescGZIP() []byte {
	file_GolangLab_proto_rawDescOnce.Do(func() {
		file_GolangLab_proto_rawDescData = protoimpl.X.CompressGZIP(file_GolangLab_proto_rawDescData)
	})
	return file_GolangLab_proto_rawDescData
}

var file_GolangLab_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GolangLab_proto_goTypes = []interface{}{
	(*TestRQ)(nil), // 0: GolangLabSvr.TestRQ
	(*TestRS)(nil), // 1: GolangLabSvr.TestRS
}
var file_GolangLab_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GolangLab_proto_init() }
func file_GolangLab_proto_init() {
	if File_GolangLab_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GolangLab_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GolangLab_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GolangLab_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GolangLab_proto_goTypes,
		DependencyIndexes: file_GolangLab_proto_depIdxs,
		MessageInfos:      file_GolangLab_proto_msgTypes,
	}.Build()
	File_GolangLab_proto = out.File
	file_GolangLab_proto_rawDesc = nil
	file_GolangLab_proto_goTypes = nil
	file_GolangLab_proto_depIdxs = nil
}
